CREATE TABLE PRODUCT(
PRODUCT_ID VARCHAR(50) PRIMARY KEY,
P_NAME VARCHAR(50) NOT NULL,
PRICE NUMBER NOT NULL,
DESCRIPTION VARCHAR(100),
STOCK NUMBER NOT NULL
);

DROP TABLE PRODUCT;

COMMENT ON COLUMN PRODUCT.PRODUCT_ID IS '상품아이디';
COMMENT ON COLUMN PRODUCT.P_NAME IS '상품명';
COMMENT ON COLUMN PRODUCT.PRICE IS '상품가격';
COMMENT ON COLUMN PRODUCT.DESCRIPTION IS '상품상세정보';
COMMENT ON COLUMN PRODUCT.STOCK IS '재고';

UPDATE PRODUCT
SET PRODUCT_ID = 'pc_ibm'
WHERE PRODUCT_ID = 'nb_ibm';

commit;