--1

SELECT DEPT_CODE, JOB_CODE, SALARY
FROM EMPLOYEE
GROUP BY DEPT_CODE;

SELECT DEPT_CODE, JOB_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE, JOB_CODE;

-- GROUP BY 에 없는 컬럼을 SELECT 에서 명시하면 안된다. 집계함수는 가능

CREATE USER 계정명 IDENTIFIED BY 비번;

GRANT CONNECT, RESOURCE TO 계정명;

ALTER TABLE TB_PRODUCT ADD PRIMARY KEY(PNO);
ALTER TABLE TB_PRODUCT ADD PRIMARY KEY
